version: '3.3'
services:
  router:
    image: traefik
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.web.address=:80'
#      - '--certificatesresolvers.myresolver.acme.caserver=https://api.letsencrypt.org/directory'
      - '--certificatesresolvers.myresolver.acme.httpchallenge=true'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
      - '--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web'
#      - '--log.level=debug'
    ports:
      - '80:80'
      - '8080:8080'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './traefik/letsencrypt:/letsencrypt'
    labels:
        - traefik.enable=true
    restart: unless-stopped

  api:
    image: 'bv-api:latest'
    environment:
      CONFIG_PATH: /app/data/config.toml
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.soberanacraft.net`)
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=myresolver
      - traefik.http.routers.api.entrypoints=websecure
    volumes:
      - './config/api:/app/data/'
      - type: bind
        source: /world-data/api/database.db
        target: /app/database.db
    restart: unless-stopped

  proxy:
    image: 'infrared-arm:latest'
    volumes:
      - './config/infrared:/configs'
    ports:
      - '25565:25565/tcp'
    links:
      - survival
    restart: unless-stopped

  survival:
    image: 'itzg/minecraft-server:latest'
    container_name: mc-season2
    environment:
      EULA: 'TRUE'
      VERSION: 1.19.3
      MEMORY: "10G"
      USE_AIKAR_FLAGS: true
      ONLINE_MODE: 'FALSE'
      TYPE: QUILT
      PACKWIZ_URL: 'https://blocovermelho.github.io/server-mods/pack.toml'
      SEED: 1921066967051512694
      DIFFICULTY: 'hard'
      SPAWN_PROTECTION: 0
    tty: true
    stdin_open: true
    ports:
        - "24454:24454/udp"
    volumes:
      - './config/survival/config:/config'
#      - './config/survival/mods:/mods'
      - '/world-data/season2:/data'
    links:
        - api
    restart: unless-stopped
