version: '3.3'
services:
  router:
    image: traefik
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.web.address=:80'
      - '--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory'
      - '--certificatesresolvers.myresolver.acme.storage=acme.json'
      - '--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web'
    ports:
      - '80:80'
      - '8080:8080'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './traefik/letsencrypt:/letsencrypt'
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.generic.entrypoints=websecure
        - traefik.http.routers.generic.tls=true
        - traefik.http.routers.generic.certresolver=myresolver

  api:
    image: 'soberana-api:latest'
    environment:
      CONFIG_PATH: /app/data/config.toml
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.soberanacraft.localhost`)
    volumes:
      - './config/api:/app/data/'

  proxy:
    image: 'haveachin/infrared:latest'
    volumes:
      - './config/infrared:/configs'
    ports:
      - '25565:25565/tcp'
    links:
      - survival

  survival:
    image: 'itzg/minecraft-server:latest'
    container_name: mc-season2
    environment:
      EULA: 'TRUE'
      VERSION: 1.19.3
      MEMORY: "1G"
      USE_AIKAR_FLAGS: true
      ONLINE_MODE: 'FALSE'
      TYPE: QUILT
      PACKWIZ_URL: 'https://blocovermelho.github.io/server-mods/pack.toml'
      VANILLATWEAKS_FILE: '/config/vt/datapacks.json'
    tty: true
    stdin_open: true
    ports:
        - "24454:24454/udp"
        - "25565:25565/udp"
        - "19132:19132/udp"
    volumes:
      - './config/survival/config:/config'
      - './config/survival/mods:/mods'
      - './config/vt:/config/vt'
    links:
        - api
